### PR TITLE
Replace @lang graphql by heredoc

### PR DESCRIPTION
**Pull request by simPod**
- [ ] Added automated tests
- [ ] Documented for all relevant versions
- [ ] Updated the changelog

**Changes**

I was thinking what about moving to heredoc from @lang?

**Breaking changes**

N/A

### CODE REVIEW

**Comment by spawnia** [comment]
This does not achieve what i want out of the `@lang` annotations: Syntax highlighting in PhpStorm.

image

**Comment by simPod** [comment]
I use it within language injections setup. Will try to reach jetbrains to make it default

**Comment by spawnia** [comment]
Sure, we can reconsider then!

**Comment by simPod** [comment]
Cross link https://youtrack.jetbrains.com/issue/WI-58861

**Pull request closed without merging**
