### PR TITLE
Review

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by spawnia** [comment]
Hey @simPod I pretty much fixed everything in https://github.com/spawnia/sailor/pull/68 - can you check if something is missing?

**Comment by simPod** [comment]
I'll compare to my changes and remove those that solve what you've solved. Gimme sec.

**Comment by simPod** [comment]
@spawnia one more thing, otherwise lgtm

**Comment by spawnia** [comment]
Fixed polymorphic mappings, too.

**Pull request closed without merging**
